[workspace]
resolver = "2"
members = [
    "src/cli",
    "src/daemon",
    "src/lib",
    "src/plugin_nispor",
    "src/plugin_baize",
]

[workspace.package]
version = "0.1.0"
authors = ["Gris Ge"]
description = "Linux Network Management Tool"
documentation = "https://github.com/nispor/nipart"
edition = "2021"
license = "Apache-2.0"
# Abstract Unix socket need 1.70.0
# Async trait need 1.75.0
rust-version = "1.75"

[workspace.dependencies]
serde = { version = "1.0.144", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
serde_json = "1.0.87"
serde_yaml = "0.9.27"
uuid = { version = "1.6.1", default-features = false, features = ["std", "v7"] }
futures = {version = "0.3.29", default-fatures = false, features = [ "std" ] }
clap = { version = "4.4" }
nispor = { version = "1.2", git = "https://github.com/nispor/nispor" }

[workspace.dependencies.tokio]
version ="1.35.0"
default-fatures = false
features = ["net", "io-util", "rt-multi-thread", "macros", "sync", "time"]

[workspace.dependencies.tokio-util]
version ="0.7.0"
default-fatures = false
features = ["time"]

[workspace.dependencies.nix]
version = "0.26.2"
default-features = false
features = ["feature", "hostname"]
